### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by autermann** [52North/iceland#1]
* `org.n52.service`
* `org.n52.iceland`

Opinions? I do like `org.n52.iceland` more. Thats the name of the project. Why should we go with something generic?

**Comment by matthesrieke** [comment]
+1 org.n52.iceland

**Comment by bpross-52n** [comment]
+1 org.n52.iceland

**Comment by nuest** [comment]
+1 for ``org.n52.iceland``

**Comment by ahitch** [comment]
why org at the beginning? We have naming conventions https://wiki.52north.org/bin/view/Documentation/BestPracticeSoftwareRelease. If this is no longer valid, then we should update it.

**Comment by autermann** [comment]
That are rules for the product name. This is about the Java package name / Maven `groupId`.
Also, I don't think this will be a library that can be downloaded from the website but will probably only appear in some `pom.xml` as a dependency.

**Comment by ahitch** [comment]
ok. +1 for ``org.n52.iceland``

**Comment by EHJ-52n** [comment]
+1 for ```org.n52.iceland```

**Comment by nuest** [comment]
``or.n52.iceland`` is the winner and already used.
