### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nuest** [52North/iceland#10]
**Agreement about documentation location:** Markdown files within the repository. Advantage: versioned, close to the code, text-based. Also suitable because iceland is for developers only.
## Documentation tasks
- [ ] for desctructable und constructable, i.e. the iceland lifecycle
- [ ] for best practices (or: options) regarding configuration files, see https://github.com/52North/SOS/pull/242#issuecomment-113396596
- [ ] _How to develop an OGC service with iceland?_
- [ ] Fix all `// TODO` statements in the code, see https://github.com/52North/iceland/search?utf8=%E2%9C%93&q=%2F%2F+TODO (empty class comments could just be removed...)

**Comment by nuest** [comment]
@bpross-52n Feed free to add documentation tasks from your perspective to the first entry.

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/5.
