### ISSUE TITLE
Configurable settings objects' init method

### ISSUE THREAD

**Issue by lestarcdog** [52North/iceland#13]
I'd like to initiate my [configurable object](https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/config/annotation/Configurable.java) after all the settings values had been assigned to my intance. Is it possible with the current version?

Because now the user needs to restart the whole application to restart e.g: the Elasticsearch client module with the new settings.

**Comment by autermann** [comment]
That should work out of the box:

```java
@Configurable
public class MyObject implements Constructable {
	private String mySetting;

	@Setting("mySetting")
	public void setMySetting(String mySetting) {
		this.mySetting = mySetting;
	}

	@Override
	public void init() {
		Objects.requireNonNull(this.mySetting);
	}
}
```

But be aware, that these settings are dynamic and may change (so the setter may be called again).

**Comment by autermann** [comment]
To be clear: the Lifecycle is `MySetting()`, `@Inject` `@Setting`, `Constructable#init()`, …, (`@Setting`)*…, `Destroyable#destroy()`.

**Comment by lestarcdog** [comment]
Thanks for the answer. I currently user the Springframework's InitializingBean interface and it is called after all the `@Settings` variable have been assigned so it is working (or should I avoid spring dependencies in my class code and use the `@Contructable` interface instead?).

**Comment by autermann** [comment]
The general idea is to be able to replace Spring e.g. with Guice, so most code should just rely on JSR330, `@PostConstruct` and `@PreDestroy`, but as `@PreDestory` can't be inherited in Spring, we created our own API, that we can map to every DI container…

So yeah, you should use `Constructable` (it's an interface and not an annotation).
