### ISSUE TITLE
Remove SOS specific classes

### ISSUE THREAD

**Issue by nuest** [52North/iceland#17]
* https://github.com/52North/iceland/search?utf8=%E2%9C%93&q=sos
* https://github.com/52North/iceland/search?utf8=%E2%9C%93&q=sensor&type=Code

**Comment by EHJ-52n** [comment]
I think, that keeping SOS constants like WPS constants in Iceland is a goog idea. 

@nuest you might link specific files that could be removed from Iceland because they are to SOS service implementation specific.

**Comment by nuest** [comment]
Why do you think keeping the constants here is a good idea?

Here's the list of specific files:

* https://github.com/52North/iceland/blob/82f3c3fec05cdbb8d9be33564d273688078f2973/src/main/java/org/n52/iceland/ogc/sos/SosConstants.java
* https://github.com/52North/iceland/blob/635372af3609c8a8844e943be2da91558bf060ef/src/main/java/org/n52/iceland/ogc/sos/Sos2Constants.java
* https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/ogc/sos/Sos1Constants.java
* https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/ogc/sos/ConformanceClasses.java
  * these classes are used in other classes, even abstract ones!
    * AbstractXmlBinding > https://github.com/52North/iceland/blob/aad82dba8ea648f0f9cdbb5fc86be397890e5368/src/main/java/org/n52/iceland/binding/pox/PoxBinding.java
    * https://github.com/52North/iceland/blob/593f5c7f00a9abce06b1b55988b48e5f86d3806c/src/main/java/org/n52/iceland/binding/soap/SoapBinding.java
* https://github.com/52North/iceland/blob/82f3c3fec05cdbb8d9be33564d273688078f2973/src/main/java/org/n52/iceland/service/MiscSettings.java
  * only the SOS-specific settings
* module ``org.n52.iceland.ogc.sos``, e.g. https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/ogc/sos/CapabilitiesExtension.java


I did not list all the **code comments** still mentioning SOS and **log statements**, they should all be rephrased.

**Comment by nuest** [comment]
bump - imho this should be solved before there is a release of iceland.

**Comment by nuest** [comment]
Or maybe not :-) I don't think that constants need to be removed anymore, and we want regular releases of iceland anyway.
