### ISSUE TITLE
Settings API - Custom action button

### ISSUE THREAD

**Issue by lestarcdog** [52North/iceland#18]
Would it be possible to have a custom button on the admin settings page?
When the user clicks on the button it should validate only a sub-group of settings fields.

Is it possible to implement this feature?

**Comment by nuest** [comment]
I would even extend on that: When the user clicks a button, it should be possible to change the state of the button ("on", "off", "ongoing operation", ..??) , and to trigger any server - side code, which might actually not be related to settings.

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/13.
