### ISSUE TITLE
License and distribution

### ISSUE THREAD

**Issue by autermann** [52North/iceland#2]
Any objections to Apache? Also I would propose to publish this package in Maven Central from the beginning.

**Comment by matthesrieke** [comment]
depends on the dep licenses :-)

**Comment by matthesrieke** [comment]
suggestion: create a first version and I we can check the licenses than.

**Comment by nuest** [comment]
Apache must be the goal for such a middleware solution, and imho it would be worth leaving out functionality to achieve that. But @matthesrieke suggestion probably works best to start.

**Comment by autermann** [comment]
We'll have dependencies on SLF4J (MIT), Guava (Apache) and Joda-Time (Apache). Additionally maybe Jackson (Apache).

The SOS core currently has a dependency on JTS (LGPLv3), but I think we can leave that out…

**Comment by matthesrieke** [comment]
than ASL 2.0 is fine.
