### ISSUE TITLE
IPv6 of the IPv4 address format exception

### ISSUE THREAD

**Issue by lestarcdog** [52North/iceland#20]
I'd like to make a query against the new SOS 5.x deployment and in the logs the following message appears.

`2015-07-06 07:32:18,193 WARN [http-nio-127.0.0.1-8080-exec-31] [ProxyChain.java:133] Ignoring invalid IP address in X-Forwared-For header: ::ffff:217.173.34.182
java.lang.IllegalArgumentException: '' is not an IP string literal.
    at com.google.common.net.InetAddresses.forString(InetAddresses.java:153) ~[InetAddresses.class:na]
    at org.n52.iceland.util.net.IPAddress.parse(IPAddress.java:125) ~[IPAddress.class:na]
    at org.n52.iceland.util.net.IPAddress.<init>(IPAddress.java:59) ~[IPAddress.class:na]
    at org.n52.iceland.util.net.ProxyChain.getIPAddress(ProxyChain.java:141) ~[ProxyChain.class:na]
    at org.n52.iceland.util.net.ProxyChain.fromForwardedForHeader(ProxyChain.java:128)`

full stacktrace: https://gist.github.com/lestarcdog/897d32d8198b29622e79

**Comment by EHJ-52n** [comment]
Looks like you this the missing IPv6 support in the org.n52.iceland.util.net package.
Do you use an IPv6 network set-up for your SOS deployment?

**Comment by nuest** [comment]
Well, you configured the demo server, you tell us :-)

**Comment by EHJ-52n** [comment]
> Ignoring invalid IP address in X-Forwared-For header: ::ffff:217.173.34.182

It seems that the requester is using an IPv6 address. 

@lestarcdog Is your IP 217.173.34.182 and nginx, or tomcat created the IPv6 stuff?

**Comment by lestarcdog** [comment]
It was my IP from Hungary. But the nginx converts it into IPv6 so the prefix ::ffff: needs to be chopped somewhere.

**Comment by nuest** [comment]
We can do the chopping within the webapp. We probably have to, unless we can tell nginx not to add the prefix.

If we do it in the webapp, it should happen within iceland, and it should be covered by a lot of unit tests :-)

**Comment by EHJ-52n** [comment]
We should make the net package IPv6 ready, and not only chop this. In addition, the nginx configuration should be updated to not add this information.

**Comment by autermann** [comment]
> `::ffff:217.173.34.182`

Thats called a [*IPv4-Mapped IPv6 Address*](https://tools.ietf.org/html/rfc4291#section-2.5.5.2).

:+1: for not working around this problem, but fixing `ProxyChain`, `IPAddress`, `IPAddressRange` and so on to support IPv6.

btw: the XFF header addresses are **not** [colon-seperated](https://github.com/52North/iceland/blob/develop/src/main/java/org/n52/iceland/util/net/ProxyChain.java#L141), but comma-seperated...

**Comment by nuest** [comment]
@CarstenHollmann Can you please discuss @52N if there are resources for this bugfix in the next couple of weeks, or if @lestarcdog should have a try himself? Thanks!

If @lestarcdog should try it, we probably need a bit longer list of classes that must be fixed, or maybe @autermann can provide the unit/integration tests that must be covered.

**Comment by nuest** [comment]
Hi guys. Any updates?

**Comment by lestarcdog** [comment]
With this couple of lines of code the IPv4 mapped IPv6 addresses can be overcome 
```
InetAddress byName = InetAddress.getByName("::ffff:217.173.34.182");    
byName.getHostAddress(); // returns 217.173.34.182
InetAddresses.isMappedIPv4Address("::ffff:217.173.34.182") // returns true
```

I think I would start with the IpAddress class and see how far it propagates.
`asByteArray()` - doesn't get called
`asInetAddress()` - indirectly in `toString()` 
`asInt()` - in [IpAddressRange](https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/util/net/IPAddressRange.java)
`asString()` - in test classes and in `toString()`
`compareTo(IPAddress)` - now compares them as int but IPv6 is 128 bits so it needs BigDecimal or 2 longs or some other datastructure.

Possible caveats:
* Somewhere in the code something depends on the string literal xxx.xxx.xxx.xxx IPv4 format.
* Something depends on that the IPv4 can be an integer.
* User field with `ip:port` format is not valid with IPv6 `[ip]:port`
* CIDR is mandatory instead of subnetmask (e.g [we do not need this in IPv6](https://github.com/52North/iceland/blob/be44477a07c9f2d950b13bd4ebde8575cc2c4872/src/main/java/org/n52/iceland/util/net/IPAddressRange.java#L73) 
* Storage field size in the database (Elasticsearch has Ip field also but it is ionly for IPv4)
* Statistics Maxmind GeoLocation transformation is only with IPv4
* Leading zero suppression and zero groups omission `2001:db8:85a3::8a2e:370:7334`

Any thoughts?

**Comment by nuest** [comment]
@autermann Is this correctly labelled as a bug, or is this not a big issue?

**Comment by autermann** [comment]
Well, we're not supporting IPv6. For me that's a bug...

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/14.
