### ISSUE TITLE
Sonar code analysis

### ISSUE THREAD

**Issue by nuest** [52North/iceland#21]
We should add iceland to our Sonar instance at http://build.dev.52north.org/sonar/

**Comment by EHJ-52n** [comment]
This requires some one to create a build job in our jenkins which provides the analysis to sonar.

**Comment by CarstenHollmann** [comment]
Build job is created. 
See code analysis here http://build.dev.52north.org/sonar/dashboard/index/8247

**Comment by nuest** [comment]
@CarstenHollmann I get an error message "The requested project does not exist. Either it has never been analyzed successfully or it has been deleted."

**Comment by CarstenHollmann** [comment]
@nuest The name has changed and thus probably the index.
See code analysis here: https://build.dev.52north.org/sonar/dashboard/index/9136
Or go to https://build.dev.52north.org/sonar/ and check for ```52°North Iceland Aggregator Project```

**Comment by autermann** [comment]
Findbugs and Checkstyle are executed for every build...
