### ISSUE TITLE
M2E Lifecycle Mapping Plugin Configuration

### ISSUE THREAD

**Issue by autermann** [52North/iceland#28]
IMHO this is IDE specific and should not be committed to version control, especially as it looks like there are [alternatives](https://mahichir.wordpress.com/2014/05/14/solving-the-plugin-execution-not-covered-by-lifecycle-configuration-error-in-eclipse/). Any objections?

**Comment by nuest** [comment]
+1 for "alternatives"

Afaics already fixed within https://github.com/52North/SOS/pull/315

**Comment by shane-axiom** [comment]
+1 for keeping this out of code. Recent versions of Eclipse fix this problem by moving the ignore settings to workspace configuration rather than project configuration.
