### ISSUE TITLE
Common logger name?

### ISSUE THREAD

**Issue by nuest** [52North/iceland#29]
Do we need a common name for loggers? I've seen `log`, `LOG` and `LOGGER` in iceland source code.

I prefer `log`, even though it is against code conventions because it is a final variable.

**Comment by autermann** [comment]
I also prefer `log`. `LOGGER` and `LOG` both somehow imply that these are constants (on which I don't want to call methods...). But everybody likes conventions (Sonar in particular), so I switched to `LOG` a while back, but I would be more than happy to switch again...

:+1:  for `log`

**Comment by nuest** [comment]
@CarstenHollmann @bpross-52n Opinions?

**Comment by bpross-52n** [comment]
My german sense for order of course demands a common name :) `log` is fine for me.

**Comment by matthesrieke** [comment]
why not get rid of `private static final Logger` at all? :)

https://github.com/jcabi/jcabi-log

yeah, it has one downside...

**Comment by CarstenHollmann** [comment]
`log` ist fine for me to

**Comment by nuest** [comment]
@matthesrieke What's the downside?

**Comment by autermann** [comment]
> @matthesrieke What's the downside?

I would assume that it calls `getClass()` for every log statement. That's quite expensive...

**Comment by matthesrieke** [comment]
it might have a hashmap for that.. I just meant the inconvenient interface always requiring a `this`..

**Comment by autermann** [comment]
[Nope](https://github.com/jcabi/jcabi-log/blob/master/src/main/java/com/jcabi/log/Logger.java#L388).
