### ISSUE TITLE
Iceland's Scope

### ISSUE THREAD

**Issue by autermann** [52North/iceland#3]
What should Iceland contain?

* Basic service componentes
* Basic API: binding, coding, requests, responses, ....
* Binding repository
* Coding repository
* Service respository
* Settings solution of SOS 4.x
* ~~Test client~~
* Converter ~~(e.g. coordinate transformator)~~
* ~~Hibernate SessionFactory~~
* Event bus

[copied from wiki]

**Comment by autermann** [comment]
First objection: do we really want a dependency to Hibernate? Thats not a common use case for all services and should be kept as SOS internal...

**Comment by matthesrieke** [comment]
yea, remove the hibernate dep. lets keep this as small as possible. also converter seems out of scope to me. This could be part of another project (e.g. OXF...)

**Comment by nuest** [comment]
Second objection: Converter - also not needed in other projects (i.e. the WPS) right now.

Imho iceland should focus on an API for request/response handling and configuring bindings/codings (inlcluding the mentioned repositories) and (very important) the flexible settings solution.

Third objection: Test client. It would be great to have a common codebase for UI and server backends, but I fear this would hold us up and considerable increase the work to complete iceland. I say we could live with copy and pasting the test client code for now.

**Comment by autermann** [comment]
I think we can pull the converter API in, but we shouldn't have any implementations for that. The 3-4 classes won't hurt...

About the test client: you're right, the Web/GUI components shouldn't be part of Iceland. Maybe we can later introduce a iceland-web-interface package, but for now we should focus on the service backend.

**Comment by EHJ-52n** [comment]
With "Svalbard" in mind, we should extract the coding and requests modules from the API into separate modules.

**Comment by ridoo** [comment]
will this finally lead to a real OX-F 2.0? I am curious ..

**Comment by autermann** [comment]
> and (very important) the flexible settings solution

That would actually introduce a dependency to hibernate. At least if you want a backend to persist the settings…

**Comment by nuest** [comment]
ah, ok. I understand. but hibernate will give us license issues #2 - right?

@autermann can you give me a link to the converter API?

**Comment by autermann** [comment]
> @autermann can you give me a link to the converter API?

https://github.com/52North/SOS/tree/master/core/api/src/main/java/org/n52/sos/convert

**Comment by nuest** [comment]
+1 on having the converter API in - that is actually quite useful.

**Comment by nuest** [comment]
@autermann Can you update the list in the first entry? Were the any additional features or things left out?

**Comment by nuest** [comment]
can we move this to a later milestone?

**Comment by nuest** [comment]
converter API is present: https://github.com/52North/iceland/tree/develop/core/src/main/java/org/n52/iceland/convert
