### ISSUE TITLE
Refactor ComparisonFilter.java

### ISSUE THREAD

**Issue by nuest** [52North/iceland#37]
The class `ComparisonFilter.java` must be refactored since it currently provides to many constructors and setters to be easily manageable. This has considerable impact on the decoders which currently take advantage of the loose available methods.

See discussion at https://github.com/52North/iceland/pull/36#discussion_r40294764

Better approaches on the table so far:
- static factory methods and a single private constructor
- new fluent API

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/9.
