### ISSUE TITLE
Change schemaLocations map to a Map<String, SchemaLocation> in SchemaRepository.

### ISSUE THREAD

**Issue by CarstenHollmann** [52North/iceland#39]
change the `Map<String, Set<SchemaLocation>>` to a `Map<String, SchemaLocation>` in
https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/coding/encode/SchemaRepository.java#L63

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/8.
