### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by autermann** [52North/iceland#4]
Java 7 will reach it's end-of-life [this month](http://www.oracle.com/technetwork/java/eol-135779.html). So I would say we'll directly go with 8. Objections?

//edit: of course it's next month... we still have march...

**Comment by nuest** [comment]
+1 on Java 8 - though this might not play well with some of the SOS customers, who might have considerably longer contracts for support of Java 7...

**Comment by matthesrieke** [comment]
Imho a release of any component that migrates to Iceland (expected: SOS, WFS, maybe SES) should have a new major release (e.g. SOS 5.x.x). Than Java 8 is fine. We can still maintain maintenance branches to fix bugs and stuff for older releases.

**Comment by bpross-52n** [comment]
+1 on Java 8

**Comment by matthesrieke** [comment]
> SOS customers, who might have considerably longer contracts for support of Java 7

most likely they bought a specific version of SOS (3.x, 4.x). Should be fine imho.

**Comment by autermann** [comment]
> > SOS customers, who might have considerably longer contracts for support of Java 7

> most likely they bought a specific version of SOS (3.x, 4.x). Should be fine imho.

So, what does @simonjirka say?

**Comment by EHJ-52n** [comment]
+1 on Java 8 but this must be clearly __documented__ and __communicated__.

**Comment by nuest** [comment]
**1.8** it is - we expect the first release of iceland to be far enough in the future.

**Comment by matthesrieke** [comment]
did we check against possible support contracts already?

**Comment by nuest** [comment]
@simonjirka please not that iceland and depending software projects will require Java 1.8, since this might be relevant for support contracts.

**Comment by nuest** [comment]
Readme and POM both say Java 1.7 - what's the reason?

**Comment by CarstenHollmann** [comment]
Updated to Java 1.7 in this commit https://github.com/52North/iceland/commit/dbeb6ff2b47ebeda148c454d4e6ce8ded979a5f0
