### ISSUE TITLE
Move capabilities extension classes out of sos package

### ISSUE THREAD

**Issue by nuest** [52North/iceland#42]
The class https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/ogc/sos/CapabilitiesExtension.java and related classes should be in an `ows` package, not in `org.52n.iceland.ogc.sos`.

**Comment by autermann** [comment]
The `CapabilitiesExtension` can now be found in `org.n52.shetland.ogc.ows.extension`
