### ISSUE TITLE
Documentation for BP to add additional endpoints

### ISSUE THREAD

**Issue by nuest** [52North/iceland#5]
Iceland will only support one endpoint (`/service`) using one servlet, so it is out of scope to generically define additional endpoints.

However, I think it would be useful to have a common practice (or documentation) how to add more endpoints. Do I have to add a new Servlet to the web.xml? Ist the /service endpoint defined manually or using some annotation? How can I combine iceland with a Spring application (even though there is no Spring in iceland)?

**Comment by nuest** [comment]
@autermann will you be able to provide guidelines or an example? I assume although there is Spring in iceland for DI, we cannot use Spring to configure additional endpoints, correct?

**Comment by nuest** [comment]
The [main servlet](https://github.com/52North/iceland/blob/303b19ebcfa9e435fddac583b36f9cd71f957cb7/src/main/java/org/n52/iceland/service/Service.java#L57) uses the ``@RequestMapping`` annotation from Spring. So there is real Spring in Iceland now? 

What about ``@WebServlet``?

**Comment by autermann** [comment]
There is Spring in Iceland. And the Spring documentation is quite extensive...
