### ISSUE TITLE
Discuss practice of constant strings

### ISSUE THREAD

**Issue by nuest** [52North/iceland#51]
See most importantly https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/util/Constants.java

**Is this good practice?**

**Comment by autermann** [comment]
IMHO, no. They we're introduced to get rid of warnings in SonarQube (like magic numbers for these ridiculous hash code constants). Well, at least the constants containing just a single character that are named after the character (e.g. `char COMMA_CHAR = ','` or `String COMMA_STRING = ","`).

Others (like `CSV_TOKEN_SEPARATOR`, `EPSG_WGS84` or `DEFAULT_ENCODING`), where the constants value can be changed without changing the constants name, seem legit to me...
