### ISSUE TITLE
Maven modules

### ISSUE THREAD

**Issue by nuest** [52North/iceland#52]
Let's discuss how we might split up the Java classes of iceland into Maven modules. This is imho not urgent but might facilitate use in later releases:
- `iceland-swes` (for all SWE-specific services), see #47 
  - could include packages `...sos.`, `...swe.`, `...swes.` 
- `iceland-config` - _Would it be feasible to use the configuration meachnism without anything else?_ 
- ... (leave comments or update this list)

**Comment by autermann** [comment]
What about modules for bindings, that pull in additional dependencies:
* `iceland-json`
* `iceland-xmlbeans`

**Comment by autermann** [comment]
I think this is already resolved with the introduction of Svalbard, Shetland and Faroe.
