### ISSUE TITLE
Automated tests of downstream services

### ISSUE THREAD

**Issue by nuest** [52North/iceland#53]
I guess it is possible somehow, but I don't know the best way: How can we automate tests of downstream services, i.e. if there is a new PR on iceland, the depending projects (e.g. SOS `5.x` branch and WPS `4.0` branch) are build with integration tests?

**Comment by autermann** [comment]
Some suggestions (ordered ascending by their effort :smiley:)

* we could handle iceland like any other dependency, upgrade occasionally and test if something is broken
* we could trigger Travis builds for SOS/WPS from each iceland build, but that will only work as long they are using the snapshot and we're not changing the version
* we could configure Jenkins to trigger downstream builds, but I think there's the same problem regarding versions
* we could add an additional integration test to the Travis build of iceland that checks out a list of projects/specific branches, updates the iceland dependency to the currently build version and builds the projects

**Comment by autermann** [comment]
Kind of solved in https://github.com/52North/travis-tools#trigger-buildsh
