### ISSUE TITLE
Response Event

### ISSUE THREAD

**Issue by lestarcdog** [52North/iceland#6]
There is an ongoing enhancement entry under the SOS issues regarding the ResponseEvent.  [Issue 216](https://github.com/52North/SOS/issues/216)

Would it be possible to have also an appropriate ResponseContext implemented in the Iceland project to store additional meta-data (e.g. execution time of the process)?

**Comment by EHJ-52n** [comment]
:+1:

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/17.
