### ISSUE TITLE
RequextContext Binding type

### ISSUE THREAD

**Issue by lestarcdog** [52North/iceland#7]
Would it be acceptable if to the [RequstContext class](https://github.com/52North/iceland/blob/e36041b417519dae004b39c5e68a22ac2c2503c9/src/main/java/org/n52/iceland/request/RequestContext.java) a new member field would be added?

The new field should represent from which Binding type the request came (i.e: JSON,SOAP,KVP...) and the member value would be then the value of JSONBinding.class, KvpBinding.class (subclasses of the SimpleBinding class), etc...
Something along this line:
`private Optional<Class> bindingClass = Optional.absent();`

The member field value would be initialized at this point:
[SimpleBinding class](https://github.com/52North/SOS/blob/e0eeee8cb5df425908b6d13df02fcec30d24d3d7/core/api/src/main/java/org/n52/sos/binding/SimpleBinding.java#L88)

Do you see any hindrance of this addition?
It would be an elegant metrics to the statistics module.

**Comment by autermann** [comment]
Do you really need the binding *class*? Or do you want to know the content type of the request?

It would be more generic, will probably work with new bindings and you won't have a dependency to the actual bindings.

While we're at it, we also can add the response media type (as the `PoxBinding` can generate a JSON response depending on the `Accept` header).

**Comment by lestarcdog** [comment]
Yes actually the content type of the request has the value for me.
The `Accept` header would be also great.

**Comment by nuest** [comment]
+1 for content type and response type.

**Comment by nuest** [comment]
@autermann What should be the next step. Should Csaba create a pull request with the changes for Iceland, or can you do the implementation?

**Comment by nuest** [comment]
@lestarcdog What is the status?

**Comment by lestarcdog** [comment]
The (ResponseEvent commit)[https://github.com/lestarcdog/SOS/commit/70a8828c31694da337928b8097f6b55ac634f890] was added to the still pending PR.

**Comment by nuest** [comment]
The PR is https://github.com/52North/SOS/pull/240

@autermann  After this is accepted and merged by the SOS devs, we need the same PR for iceland, correct?

**Comment by lestarcdog** [comment]
I'd like to bump this issue again.

I think my modification of the [RequestContext class] (https://github.com/52North/iceland/blob/063b219b58f8cecd6183c3b8ac7bd522941cfd3b/src/main/java/org/n52/iceland/request/RequestContext.java) has a room for a little bit of improvement. The conversion of the Accept header from String to `List<MediaType>` is redundant. I'd be more comfortable if only the String version of the `Accept` header would be stored. 

When I need it in my statistics module I could convert it with the [HTTPUtils#getAcceptHeader](https://github.com/52North/iceland/blob/635372af3609c8a8844e943be2da91558bf060ef/src/main/java/org/n52/iceland/util/http/HTTPUtils.java#L80) function which needs to be overloaded to accept String as a parameter as well.

Is this modification sound to you?

**Comment by nuest** [comment]
Why do you say the conversion is redundant? Would a string actually be easier for your to work with?

Also, some bad news: @autermann is on vacation and won't be able to help us with the decision during the next two weeks. We might have to work on our on branches for a little while.

**Comment by lestarcdog** [comment]
@nuest I think it is redundant in a sense that if the statistics collection module is turned off nobody will read that field so the conversion is unnecessary.

**Comment by autermann** [comment]
Right now, it's not used anywhere else, but I would propose to keep it like that. Sooner or later `SimpleBinding#writeResponse()` and `SimpleBinding#writeOwsExceptionReport()` will use that instead of extracting the header themself...
