### ISSUE TITLE
Broken Links in Documentation

### ISSUE THREAD

**Issue by cDanowski** [52North/iceland#71]
I just noticed that any Link to a Java resource is broken due to the fact, that there is no ```src``` folder on top-level of the repository. Instead there are two folders ```core``` and ```util```, which contain the ```src``` folders. 

So, each link has to be changed in order to contain the missing ```.../core/...``` or ```.../util/...``` part.

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/6.
