### ISSUE TITLE
Documentation of information flow

### ISSUE THREAD

**Issue by nuest** [52North/iceland#9]
The SOS documentation has a nice figure on how the different classes are related to each other and how the information flows through it. This should be adjusted for Iceland and added to the documentation (could be stored as attachment in the wiki)

![SOS architecture](https://wiki.52north.org/pub/SensorWeb/SensorObservationServiceIVDocumentation/sos_architecture.png)

**Comment by nuest** [comment]
@EHJ-52n can provide the sources for the graphic...

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/4.
